### ISSUE TITLE
Feature request: hide exceptions and error from `execa`

### ISSUE THREAD

**Issue by kwonoj** [gnpaone/rust-just#14]
Hi, curious if it's possible to hide the error from `execa` and only shows just's output, when a recipe's exit code is non zero, `execa` always emits its own error to the bottom so to look for the actual error have to scroll up redundant part.

```
...output from recipe..

error: Recipe `run-cli` failed on line 105 with exit code 1
file:///Users/someuser/repo/node_modules/rust-just/node_modules/execa/lib/return/final-error.js:6
	return new ErrorClass(message, options);
	       ^

ExecaError: Command failed with exit code 1: /Users/someuser/repo/node_modules/rust-just-darwin-arm64/bin/just --justfile packages/somepath/JUSTFILE run-cli '[redacted]' add-event
    at getFinalError (file:///Users/someuser/repo/node_modules/rust-just/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///Users/someuser/repo/node_modules/rust-just/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///Users/someuser/repo/node_modules/rust-just/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///Users/someuser/repo/node_modules/rust-just/node_modules/execa/lib/methods/main-async.js:150:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///Users/someuser/repo/node_modules/rust-just/lib/index.mjs:33:25) {
  shortMessage: "Command failed with exit code 1: /Users/someuser/repo/node_modules/rust-just-darwin-arm64/bin/just --justfile packages/somepath/JUSTFILE run-cli '[redacted]' add-event",
  command: '/Users/someuser/repo/node_modules/rust-just-darwin-arm64/bin/just --justfile packages/somepath/JUSTFILE run-cli [redacted] add-event',
  escapedCommand: "/Users/someuser/repo/node_modules/rust-just-darwin-arm64/bin/just --justfile packages/somepath/JUSTFILE run-cli '[redacted]' add-event",
  cwd: '/Users/someuser/repo',
  durationMs: 1104.241167,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  exitCode: 1,
  stdio: [ undefined, undefined, undefined ],
  ipcOutput: [],
  pipedFrom: []
}

Node.js v20.15.1
```

The actual error message appears up above `error: Recipe run-cli failed on line 105 with exit code 1`.

**Comment by kwonoj** [comment]
Maybe utilizing https://github.com/sindresorhus/execa/blob/HEAD/docs/errors.md#preventing-exceptions, allow to opt-in to throw?

**Comment by gnpaone** [comment]
Sure, I'll modify code to hide the ExecaError. It'll be available in the next release

**Comment by gnpaone** [comment]
Done 👍. By default it hides the error. You can choose to show the error using `--execaoptions '{"reject": true}'` argument as well as you can pass other execa options in json format. You can test it by cloning this repo and running `yarn install` and `yarn dev [OPTIONS] [ARGUMENTS]...` inside `npm/rust-just` directory

**Comment by gnpaone** [comment]
[1.37.0](https://www.npmjs.com/package/rust-just) is released.
